### ISSUE TITLE
Datasets with datatype float16 cannot be displayed in HDFView

### ISSUE THREAD

**Issue by nup002** [h5py/h5py#1551]
**System info**
 * Operating System: Windows 10 64-bit
 * Python version: 3.8
 * Anaconda
 * h5py version: 2.10.0
 * HDF5 version: 1.10.4
 * HDFView version : 3.1.0

**Description of issue:**
HDFView cannot display datasets created with dtype=np.float16. When double-clicking the dataset in HDFView, the following error is presented:
```
An error occurred when loading data for the table:
data value is null
```
It is possible that this bug is solely in the ballpark of the HDF5 group, but I am still posting it here for posterity in case others run into the same issue.

**Steps to reproduce error:**
First, create a new file and the float16 dataset:
```
import h5py
import numpy as np
file = h5py.File("Myfolder/Myfile.hdf5", 'a')
dset = file.create_dataset('A_float16_dataset', shape=(1,), dtype=np.float16)
file.flush()
file.close()
```
Then, open the file in HDF5view and double-click the dataset `'A_float16_dataset'`. The error will appear. This error appears regardless of whether data has been written to the dataset or not.

**Comment by takluyver** [comment]
I can reproduce that with HDFView 3.1.0. But `h5ls` and `h5dump` show it fine, as does HDFView 2.1.3:

![Screenshot from 2020-05-18 22-07-42](https://user-images.githubusercontent.com/327925/82260222-c33bcc00-9954-11ea-90f7-5a8fae45afd6.png)

So it seems to be a problem with HDFView, not with h5py creating the file. You should see if it's fixed in 3.1.1 (https://www.hdfgroup.org/downloads/hdfview/ ), and if not, [tell HDF group](https://portal.hdfgroup.org/display/support/The+HDF+Help+Desk).

**Comment by nup002** [comment]
Thank you. Error persists in HDFView 3.1.1. 
I will let the HDF group know. Good to know this is not a problem caused by h5py.

**Comment by G-nn-r** [comment]
FYI: I reported this bug here: https://github.com/HDFGroup/hdfview/issues/335
